/*
Copyright 2026 LeaoMartelo2 (https://github.com/LeaoMartelo2)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef C2HTML_H
#define C2HTML_H

#include <assert.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

#define C2HTML_VERSION_MAJOR 2
#define C2HTML_VERSION_MINOR 0
#define C2HTML_VERSION_PATCH 0

static FILE *c2html_outfile = NULL;
static char *__filename = NULL;
static char *js_file = NULL;
static char *css_file = NULL;

typedef struct {
    const char *css_path;
    const char *js_path;
    const char *title;

} c2html_init_opt_args;

static inline void c2html_init_opt(const char *file, c2html_init_opt_args opt) {

    if (!file) exit(1);

    c2html_outfile = fopen(file, "w");
    assert(file != NULL);

    if (opt.css_path) css_file = strdup(opt.css_path);
    if (opt.js_path) js_file = strdup(opt.js_path);
    __filename =  strdup(file);

    printf("Starting to write to %s...\n\n", file);

    fprintf(c2html_outfile, "<!--\n");
    {
        fprintf(c2html_outfile, "==== FILE AUTOMATICALLY GENERATED ====\n");
        fprintf(c2html_outfile, "This file is automatically generated by C2HTML Version %d.%d.%d\n\n", C2HTML_VERSION_MAJOR, C2HTML_VERSION_MINOR, C2HTML_VERSION_PATCH);
    }
    fprintf(c2html_outfile, "-->\n\n");

    fprintf(c2html_outfile, "<!--\n");
    {

        time_t raw_time;
        struct tm *time_info;
        char time_string[100];
        time(&raw_time);

        time_info = localtime(&raw_time);
        strftime(time_string, sizeof(time_string), "%Y-%m-%d %H:%M:%S", time_info);

        fprintf(c2html_outfile, "Page built at: %s\n", time_string);


        fprintf(c2html_outfile, "Compiled with with ");

        char version_str[100];

#if defined(__clang__)
        snprintf(version_str, sizeof(version_str), "Clang %d.%d.%d",
                __clang_major__, __clang_minor__, __clang_patchlevel__);

#elif defined(__GNUC__)
        snprintf(version_str, sizeof(version_str), "GCC %d.%d.%d",
                __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
#else
        snprintf(version_str, sizeof(version_str), "A unknown compiler");
#endif

        fprintf(c2html_outfile, "%s\n", version_str);

    }
    fprintf(c2html_outfile, "-->\n\n");

    fprintf(c2html_outfile, "<!DOCTYPE html>\n");
    fprintf(c2html_outfile, "<head>\n");
    fprintf(c2html_outfile, "<meta charset=\"utf-8\" />\n");
    fprintf(c2html_outfile, "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");

    if (opt.title) fprintf(c2html_outfile, "<title>%s</title>\n", opt.title);

    if (opt.css_path) fprintf(c2html_outfile, "<link href=\"%s\" rel=\"stylesheet\">\n", opt.css_path);

    fprintf(c2html_outfile, "</head>\n");

    fprintf(c2html_outfile, "<body>\n");
}

#define c2html_init(file, ...) c2html_init_opt(file, (c2html_init_opt_args){__VA_ARGS__})

static inline long c2html_get_file_size(const char *filename) {

    struct stat file_info;

    if (stat(filename, &file_info) != 0) {
        printf("Failed to stat file %s\n", filename);
        exit(1);
    }

    return file_info.st_size;
}

static inline void c2html_print_file_size(long size, const char *filename) {

    const char *units[] = {"bytes", "Kb", "Mb", "Gb"};
    double size_units = size;
    int index = 0;

    while (size_units >= 1024 && index < 3) {
        size_units /= 1024;
        index++;
    }

    printf("\nWritten %.2f%s to %s\n\n", size_units, units[index], filename);
}


static inline void c2html_end_file() {
    fprintf(c2html_outfile, "\n\n\n<script src=\"%s\" defer></script>", js_file);
    fprintf(c2html_outfile, "\n</body>\n");
    fprintf(c2html_outfile, "</html>\n");

    fclose(c2html_outfile);

    long size = c2html_get_file_size(__filename);
    c2html_print_file_size(size, __filename);
}

typedef struct {
    const char *css_class;
    const char *id;
    const char *src;
    const char *href;
    const double width;
    const double height;
    const char *on_click;
    const char *type;
    bool no_close;

} c2html_tag_params;

static inline void c2html_write_params(c2html_tag_params param) {
    if (param.css_class) fprintf(c2html_outfile, " class=\"%s\"", param.css_class);
    if (param.id) fprintf(c2html_outfile, " id=\"%s\"", param.id);
    if (param.src) fprintf(c2html_outfile, " src=\"%s\"", param.src);
    if (param.href) fprintf(c2html_outfile, " href=\"%s\"", param.href);
    if (param.width) fprintf(c2html_outfile, " width=\"%f\"", param.width);
    if (param.height) fprintf(c2html_outfile, " height=\"%f\"", param.height);
    if (param.type) fprintf(c2html_outfile, " type=\"%s\"", param.type);
}

#define C2HTML_CONCAT_INNER(a, b) a##b
#define C2HTML_CONCAT(a, b) C2HTML_CONCAT_INNER(a, b)

#define push_tag(tag, ...)                    \
    do {                                      \
        c2html_tag_params _p = {__VA_ARGS__}; \
        fprintf(c2html_outfile, "<" #tag);    \
        c2html_write_params(_p);              \
        fprintf(c2html_outfile, ">\n");       \
    } while (0)

#define pop_tag(tag) fprintf(c2html_outfile, "</" #tag ">\n")

static inline void push_ftag_opt(const char *tag, c2html_tag_params opt) {

    fprintf(c2html_outfile, "<%s", tag);
    c2html_write_params(opt);
    fprintf(c2html_outfile, ">");
}

#define push_ftag(tag, ...) push_ftag_opt(tag, (c2html_tag_params){__VA_ARGS__})

static inline void pop_ftag(const char *tag) {
    fprintf(c2html_outfile, "</%s>", tag);
}

#define with_tag(tag, ...)                                                                            \
    c2html_tag_params __attribute__((unused)) C2HTML_CONCAT(_params_##tag, __LINE__) = {__VA_ARGS__}; \
    fprintf(c2html_outfile, "<" #tag);                                                                \
    c2html_write_params(C2HTML_CONCAT(_params_##tag, __LINE__));                                      \
    fprintf(c2html_outfile, ">");                                                                     \
    for (struct { const char *name; c2html_tag_params *p; } _state = {#tag, &C2HTML_CONCAT(_params_##tag, __LINE__)}; _state.name != NULL; (!_state.p->no_close ? fprintf(c2html_outfile, "</%s>\n", _state.name) : 0), _state.name = NULL)

static inline void add_text(const char *format, ...) {
    va_list args;
    va_start(args, format);
    vfprintf(c2html_outfile, format, args);
    va_end(args);
}

static inline void br() { fprintf(c2html_outfile, "<br>\n"); }

static inline void br_repeat(size_t ammount) {
    for (size_t i = 0; i < ammount; ++i) {
        br();
    }
}

static inline const char *text_format(const char *text, ...) {

#ifndef MAX_TEXTFORMAT_BUFFERS
#define MAX_TEXTFORMAT_BUFFERS 4
#endif

#ifndef MAX_TEXT_BUFFER_LENGHT
#define MAX_TEXT_BUFFER_LENGHT 1024
#endif

    static char buffers[MAX_TEXTFORMAT_BUFFERS][MAX_TEXT_BUFFER_LENGHT];
    static int index;

    char *current_buffer = buffers[index];
    memset(current_buffer, 0, MAX_TEXT_BUFFER_LENGHT);

    va_list args;
    va_start(args, text);
    int required_sz = vsnprintf(current_buffer, MAX_TEXT_BUFFER_LENGHT, text, args);
    va_end(args);

    if (required_sz >= MAX_TEXT_BUFFER_LENGHT) {
        printf("Too large of a string to format:\n String passed: %s\n", text);
        exit(1);
    }

    index += 1;

    if (index >= MAX_TEXTFORMAT_BUFFERS) index = 0;

    return current_buffer;
}

#define MAX_LINE_LENGTH 1024

typedef struct {
    char **lines;
    size_t count;
} TextLines;

static inline TextLines read_file(const char *file_path) {

    FILE *file = fopen(file_path, "r");
    TextLines text_lines = {0};

    assert(file != NULL);

    printf("Reading from file: %s\n", file_path);

    char line[MAX_LINE_LENGTH];

    size_t capacity = 10;
    text_lines.lines = (char **)malloc(capacity * sizeof(char *));

    assert(text_lines.lines != NULL);

    while (fgets(line, sizeof(line), file)) {
        line[strcspn(line, "\n")] = 0;

        if (text_lines.count >= capacity) {
            capacity *= 2;
            text_lines.lines = (char **)realloc(text_lines.lines, capacity * sizeof(char *));

            assert(text_lines.lines != NULL);
        }

        text_lines.lines[text_lines.count] = (char *)malloc((strlen(line) + 1) * sizeof(char));

        assert(text_lines.lines[text_lines.count] != NULL);
        strcpy(text_lines.lines[text_lines.count], line);
        text_lines.count++;
    }

    fclose(file);

    printf("Read %zu lines from %s\n", text_lines.count, file_path);

    return text_lines;
}

#endif /* C2HTML_H */
